user rest controller
ITMO-TECH-TEAM-3/TEAM-3-1 pull request #40
Opened 2022-06-06 21:40 UTC by fadyat

👀

2022-06-08 17:43 UTC, DoKep2 requested changes

2022-06-08 17:43 UTC, DoKep2 commented on registration/src/main/java/com/team1/registration/configs/WebSecurityConfig.java
> +                    .antMatchers("/*", "/*/*", "/*/*/*", "/*/*/*/*").permitAll()
мб более по-человечески прописывается?)

2022-06-08 17:43 UTC, DoKep2 commented on registration/src/main/java/com/team1/registration/controllers/rest/UserRestController.java
> +@RequestMapping("/users-rest")
Хз насчёт слова rest в маппингах, обычно совпадает с маппингами обычного контроллера
Или там конфликты?

2022-06-08 17:43 UTC, DoKep2 commented on registration/src/main/java/com/team1/registration/models/User.java
> +    private Double balance = 0d;
Где-то слышал, что за хранения баланса в даблах руки отрывают)
Почитаю на досуге

2022-06-08 17:47 UTC, DoKep2 commented on registration/src/main/java/com/team1/registration/services/UserService.java
> +        if (!passwordEncoder.matches(user.getPassword(), userFromDb.getPassword())) {
норм

2022-06-08 17:47 UTC, DoKep2 commented on registration/src/main/java/com/team1/registration/repositories/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, UUID> {
норм

2022-06-08 17:52 UTC, fadyat commented
Cringe

2022-06-09 12:24 UTC, fadyat commented on registration/src/main/java/com/team1/registration/controllers/rest/UserRestController.java
> +@RequestMapping("/users-rest")
Конфликты конечно

2022-06-10 17:51 UTC, DoKep2 commented
## **Лайк**
![кит](https://user-images.githubusercontent.com/86494191/173123124-313f55cc-640d-43f3-bac3-9ac57bfdfa28.gif)

2022-06-10 17:52 UTC, DoKep2 approved these changes

2022-06-10 17:52 UTC, merged